/*
 * This source file was generated by the Gradle 'init' task
 */
package adventofcodeday1;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.lang.NumberFormatException;
import adventofcodeday1.DialPuzzle1;

public class App {

    public static int getMoveAmount(String instruction){

        String amountString = instruction.substring(1);

        try{

            int moveAmount = Integer.parseInt(amountString);
            return moveAmount;

        } catch (NumberFormatException e){
            System.out.println(e);
            return 0;
        } 

    }

    public static void main(String[] args) {

        //DialPuzzle1 dial1 = new DialPuzzle1();
        DialPuzzle2 dial2 = new DialPuzzle2();

        int start = 50;

        int zeroCount = 0;

        try (Scanner fileScanner = new Scanner(new File("Day1/Puzzle1/puzzle1solution/app/src/main/java/adventofcodeday1/input.txt"))){

            while(fileScanner.hasNextLine()){

                String instruction = fileScanner.nextLine();

                int moveAmount = getMoveAmount(instruction);

                System.out.println("Current pass 0 Amount:" + zeroCount);
                //int end;

                if (instruction.startsWith("L")) {
                    
                    // Dial 2 end is [passZero, endNumber]
                    int[] end = dial2.moveLeft(start, moveAmount);
                    zeroCount = zeroCount + end[0];


                    System.out.printf("Start: %d, Instruction: %s, End: %d, Pass: %d.\n", start, instruction, end[1], end[0]);

                    start = end[1];

                } else if (instruction.startsWith("R")) {

                    // Dial 2 end is [passZero, endNumber]
                    
                    int[] end = dial2.moveRight(start, moveAmount);

                    zeroCount = zeroCount + end[0];

                    System.out.printf("Start: %d, Instruction: %s, End: %d, Pass: %d.\n", start, instruction, end[1], end[0]);

                    start = end[1];

                } else {

                    continue;

                }
            }

        } catch(FileNotFoundException exception){
            System.out.println(exception);
        }

        System.out.println("Final zero count: " + zeroCount);
    }
}
