/*
 * This source file was generated by the Gradle 'init' task
 */
package adventofcodeday1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import adventofcodeday1.DialPuzzle1;

class Dial1Test {
    @Test void LeftNotBeforeZero() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 50;
        int dialLeftMove = 30;
        assertEquals(testDial.moveLeft(dialStart, dialLeftMove), 20);
    }

    @Test void LeftBeforeZero() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 50;
        int dialLeftMove = 68;
        assertEquals(testDial.moveLeft(dialStart, dialLeftMove), 82);
    }

    @Test void RightNotAfterZero() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 50;
        int dialRightMove = 30;
        assertEquals(testDial.moveRight(dialStart, dialRightMove), 80);
    }

    @Test void RightAfterZero() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 95;
        int dialRightMove = 60;
        assertEquals(testDial.moveRight(dialStart, dialRightMove), 55);
    }

    @Test void LeftMultipleTurns() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 50;
        int dialLeftMove = 368;
        assertEquals(testDial.moveLeft(dialStart, dialLeftMove), 82);
    }

    @Test void RightMultipleTurns() {
        DialPuzzle1 testDial = new DialPuzzle1();

        int dialStart = 95;
        int dialRightMove = 360;
        assertEquals(testDial.moveRight(dialStart, dialRightMove), 55);
    }

}
