/*
 * This source file was generated by the Gradle 'init' task
 */
package adventofcodeday1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import adventofcodeday1.DialPuzzle2;

class Dial2Test {
    @Test void testMultipleTurnsRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialRightMove = 1000;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {10, 50};


        assertArrayEquals(result, expected);
    }

    @Test void testSingleTurnRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialRightMove = 60;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {1, 10};

        assertArrayEquals(result, expected);
    }

    @Test void testNoTurnRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialRightMove = 40;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {0, 90};

        assertArrayEquals(result, expected);
    }

    @Test void testDoubleTurnRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialRightMove = 200;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {2, 50};

        assertArrayEquals(result, expected);
    }

    @Test void rightLandOnZeroRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialRightMove = 150;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {2, 0};

        assertArrayEquals(result, expected);
    }

    @Test void startOnZeroMultipleRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 0;
        int dialRightMove = 150;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {1, 50};

        assertArrayEquals(result, expected);
    }

    @Test void startOnZeroNoneRight() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 0;
        int dialRightMove = 30;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {0, 30};

        assertArrayEquals(result, expected);
    }

    @Test void testMultipleTurnsLeft() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 10;
        int dialLeftMove = 570;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {6, 40};

        assertArrayEquals(result, expected);
    }

    @Test void testSingleTurnsLeft() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 10;
        int dialLeftMove = 70;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {1, 40};

        assertArrayEquals(result, expected);
    }

    @Test void testNoTurnsLeft() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 70;
        int dialLeftMove = 10;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {0, 60};

        assertArrayEquals(result, expected);
    }

    @Test void landOnZeroLeft() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 70;
        int dialLeftMove = 70;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {1, 0};

        assertArrayEquals(result, expected);
    }

    @Test void  startOnZeroLeft() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 0;
        int dialLeftMove = 70;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        for(int i = 0; i < result.length; i++){
            System.out.println(result[i]);
        }

        int[] expected = {0, 30};

        assertArrayEquals(result, expected);
    }

    @Test void L100() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 0;
        int dialLeftMove = 100;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {1, 0};
        
        assertArrayEquals(result, expected);
    }
    
    @Test void L68() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 50;
        int dialLeftMove = 68;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {1, 82};
        
        assertArrayEquals(result, expected);
    }

    @Test void L30() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 82;
        int dialLeftMove = 30;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {0, 52};
        
        assertArrayEquals(result, expected);
    }

    @Test void R48() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 52;
        int dialRightMove = 48;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {1, 0};
        
        assertArrayEquals(result, expected);
    }

    @Test void L5() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 0;
        int dialLeftMove = 5;

        int[] result = testDial.moveLeft(dialStart, dialLeftMove);

        int[] expected = {0, 95};
        
        assertArrayEquals(result, expected);
    }

    @Test void R60() {
        DialPuzzle2 testDial = new DialPuzzle2();

        int dialStart = 95;
        int dialRightMove = 60;

        int[] result = testDial.moveRight(dialStart, dialRightMove);

        int[] expected = {1, 55};
        
        assertArrayEquals(result, expected);
    }

}
