/*
 * This source file was generated by the Gradle 'init' task
 */
package adventofcodeday1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import adventofcodeday1.Dial;

class DialTest {
    @Test void LeftNotBeforeZero() {
        Dial testDial = new Dial();

        int dialStart = 50;
        int dialLeftMove = 30;
        assertEquals(testDial.moveLeft(dialStart, dialLeftMove), 20);
    }

    @Test void LeftBeforeZero() {
        Dial testDial = new Dial();

        int dialStart = 50;
        int dialLeftMove = 68;
        assertEquals(testDial.moveLeft(dialStart, dialLeftMove), 82);
    }

    @Test void RightNotAfterZero() {
        Dial testDial = new Dial();

        int dialStart = 50;
        int dialRightMove = 30;
        assertEquals(testDial.moveRight(dialStart, dialRightMove), 80);
    }

    @Test void RightAfterZero() {
        Dial testDial = new Dial();

        int dialStart = 95;
        int dialRightMove = 60;
        assertEquals(testDial.moveRight(dialStart, dialRightMove), 55);
    }
}
